import os
from datetime import date, datetime
from io import BytesIO

import pandas as pd
import psycopg2
from psycopg2.extras import RealDictCursor
from psycopg2.pool import SimpleConnectionPool
import streamlit as st

st.set_page_config(page_title="TallyUp", page_icon="✏️", layout="wide")


def get_database_url():
    database_url = os.environ.get("DATABASE_URL", "")
    if not database_url:
        try:
            database_url = st.secrets.get("DATABASE_URL", "")
        except Exception:
            database_url = ""
    if not database_url:
        st.error("DATABASE_URL is missing from environment variables or .streamlit/secrets.toml.")
        st.stop()
    return database_url


@st.cache_resource(show_spinner=False)
def get_pool():
    return SimpleConnectionPool(1, 5, get_database_url(), sslmode="require")


def get_conn():
    return get_pool().getconn()


def release_conn(conn):
    get_pool().putconn(conn)


@st.cache_resource(show_spinner=False)
def init_db():
    conn = get_conn()
    cur = conn.cursor()

    cur.execute("""
    CREATE TABLE IF NOT EXISTS items (
        item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        item_name TEXT NOT NULL UNIQUE,
        buying_price REAL DEFAULT 0,
        selling_price REAL DEFAULT 0,
        current_stock REAL DEFAULT 0,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )
    """)

    cur.execute("""
    CREATE TABLE IF NOT EXISTS purchases (
        purchase_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        purchase_date TEXT NOT NULL,
        item_id INTEGER NOT NULL,
        quantity REAL NOT NULL,
        buying_price REAL NOT NULL,
        total_cost REAL NOT NULL,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(item_id) REFERENCES items(item_id)
    )
    """)

    cur.execute("""
    CREATE TABLE IF NOT EXISTS sales (
        sale_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sale_date TEXT NOT NULL,
        item_id INTEGER NOT NULL,
        quantity REAL NOT NULL,
        selling_price REAL NOT NULL,
        total_amount REAL NOT NULL,
        estimated_profit REAL NOT NULL,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(item_id) REFERENCES items(item_id)
    )
    """)

    cur.execute("""
    CREATE TABLE IF NOT EXISTS expenses (
        expense_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        expense_date TEXT NOT NULL,
        expense_name TEXT NOT NULL,
        amount REAL NOT NULL,
        remarks TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )
    """)

    cur.execute("""
    CREATE TABLE IF NOT EXISTS service_sales (
        service_sale_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sale_date TEXT NOT NULL,
        service_name TEXT NOT NULL,
        selling_price REAL NOT NULL,
        quantity REAL NOT NULL,
        total_amount REAL NOT NULL,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )
    """)

    cur.execute("ALTER TABLE items DROP COLUMN IF EXISTS category")
    cur.execute("ALTER TABLE items DROP COLUMN IF EXISTS unit")
    cur.execute("ALTER TABLE items DROP COLUMN IF EXISTS minimum_stock")
    cur.execute("ALTER TABLE purchases DROP COLUMN IF EXISTS supplier_name")
    cur.execute("ALTER TABLE purchases DROP COLUMN IF EXISTS payment_status")
    cur.execute("ALTER TABLE purchases DROP COLUMN IF EXISTS remarks")
    cur.execute("ALTER TABLE sales DROP COLUMN IF EXISTS buying_price_at_sale")
    cur.execute("ALTER TABLE sales DROP COLUMN IF EXISTS payment_method")
    cur.execute("ALTER TABLE sales DROP COLUMN IF EXISTS payment_status")
    cur.execute("ALTER TABLE sales DROP COLUMN IF EXISTS customer_name")
    cur.execute("ALTER TABLE sales DROP COLUMN IF EXISTS amount_paid")
    cur.execute("ALTER TABLE sales DROP COLUMN IF EXISTS balance")
    cur.execute("ALTER TABLE sales DROP COLUMN IF EXISTS remarks")
    cur.execute("DROP TABLE IF EXISTS stock_adjustments")

    conn.commit()
    cur.close()
    release_conn(conn)


@st.cache_data(ttl=30, show_spinner=False)
def query_df(sql, params=()):
    conn = get_conn()
    cur = conn.cursor(cursor_factory=RealDictCursor)
    try:
        cur.execute(sql, params)
        rows = cur.fetchall()
        columns = [desc.name for desc in cur.description] if cur.description else []
        return pd.DataFrame(rows, columns=columns)
    finally:
        cur.close()
        release_conn(conn)


def execute(sql, params=()):
    conn = get_conn()
    cur = conn.cursor()
    try:
        cur.execute(sql, params)
        conn.commit()
        last_id = cur.fetchone()[0] if cur.description else None
        st.cache_data.clear()
        return last_id
    except Exception:
        conn.rollback()
        raise
    finally:
        cur.close()
        release_conn(conn)


def get_items_df():
    return query_df("SELECT * FROM items ORDER BY item_name")


def get_item_options():
    df = get_items_df()
    if df.empty:
        return {}, []
    mapping = {row.item_name: int(row.item_id) for row in df.itertuples()}
    return mapping, list(mapping.keys())


def money(x):
    try:
        return f"{float(x):,.0f}"
    except Exception:
        return "0"


TRANSLATIONS = {
    "TallyUp": "TallyUp",
    "A simple stock, sales, expense, and profit tracker for a small stationery business.": "Mfumo rahisi wa kufuatilia stock, mauzo, matumizi, na faida kwa biashara ndogo ya stationery.",
    "Menu": "Menyu",
    "Dashboard": "Dashibodi",
    "Inventory/Stock": "Bidhaa/Stock",
    "Sales": "Mauzo",
    "Expenses": "Matumizi",
    "Reports": "Ripoti",
    "Export Data": "Pakua Data",
    "Sales Today": "Mauzo ya Leo",
    "Estimated Profit Today": "Makadirio ya Faida Leo",
    "Expenses Today": "Matumizi ya Leo",
    "Service Sales Today": "Mauzo ya Huduma Leo",
    "Low Stock Items": "Bidhaa Zilizo Chini",
    "Low Stock Alerts": "Tahadhari za Stock Chini",
    "No items yet. Add your first stock entry from the Inventory/Stock page.": "Hakuna bidhaa bado. Ongeza stock ya kwanza kwenye ukurasa wa Bidhaa/Stock.",
    "All items are above their minimum stock level.": "Bidhaa zote ziko juu ya kiwango cha chini cha stock.",
    "Today's Sales": "Mauzo ya Leo",
    "Inventory / Stock": "Bidhaa / Stock",
    "Date": "Tarehe",
    "Item Name": "Jina la Bidhaa",
    "Buying Price": "Bei ya Kununua",
    "Quantity": "Idadi",
    "Total Cost": "Jumla ya Gharama",
    "Save Stock": "Hifadhi Stock",
    "Item name is required.": "Jina la bidhaa linahitajika.",
    "Buying price and quantity must be greater than zero.": "Bei ya kununua na idadi lazima ziwe zaidi ya sifuri.",
    "Stock saved.": "Stock imehifadhiwa.",
    "Current Stock": "Stock ya Sasa",
    "Stock History": "Historia ya Stock",
    "Sale Type": "Aina ya Mauzo",
    "Goods": "Bidhaa",
    "Service": "Huduma",
    "Add stock first before recording goods sales.": "Ongeza stock kwanza kabla ya kurekodi mauzo ya bidhaa.",
    "Name": "Jina",
    "Available stock": "Stock iliyopo",
    "Selling Price": "Bei ya Kuuza",
    "Total": "Jumla",
    "Save Sale": "Hifadhi Mauzo",
    "Selling price and quantity must be greater than zero.": "Bei ya kuuza na idadi lazima ziwe zaidi ya sifuri.",
    "You cannot sell more than the available stock.": "Huwezi kuuza zaidi ya stock iliyopo.",
    "Sale saved and stock updated.": "Mauzo yamehifadhiwa na stock imesasishwa.",
    "Save Service Sale": "Hifadhi Mauzo ya Huduma",
    "Name is required.": "Jina linahitajika.",
    "Service sale saved.": "Mauzo ya huduma yamehifadhiwa.",
    "Goods Sales": "Mauzo ya Bidhaa",
    "Service Sales": "Mauzo ya Huduma",
    "Record Expense": "Rekodi Matumizi",
    "Expense Date": "Tarehe ya Matumizi",
    "Expense Name": "Jina la Matumizi",
    "Amount": "Kiasi",
    "Remarks": "Maelezo",
    "Optional": "Si lazima",
    "Save Expense": "Hifadhi Matumizi",
    "Expense name and amount are required.": "Jina la matumizi na kiasi vinahitajika.",
    "Expense saved.": "Matumizi yamehifadhiwa.",
    "Recent Expenses": "Matumizi ya Karibuni",
    "Start Date": "Tarehe ya Kuanza",
    "End Date": "Tarehe ya Mwisho",
    "Estimated Gross Profit": "Makadirio ya Faida Ghafi",
    "Estimated Net Profit": "Makadirio ya Faida Halisi",
    "Purchases": "Manunuzi",
    "Goods Sales Report": "Ripoti ya Mauzo ya Bidhaa",
    "Service Sales Report": "Ripoti ya Mauzo ya Huduma",
    "Inventory / Stock Report": "Ripoti ya Bidhaa / Stock",
    "Expenses Report": "Ripoti ya Matumizi",
    "Fast Moving Items": "Bidhaa Zinazouzwa Haraka",
    "Download your business records as Excel files.": "Pakua rekodi za biashara yako kama faili la Excel.",
    "Download Excel Export": "Pakua Excel",
    "date": "tarehe",
    "name": "jina",
    "quantity": "idadi",
    "selling_price": "bei_ya_kuuza",
    "buying_price": "bei_ya_kununua",
    "total_amount": "jumla",
    "estimated_profit": "makadirio_ya_faida",
    "stock_value": "thamani_ya_stock",
    "total_cost": "jumla_ya_gharama",
    "purchase_date": "tarehe_ya_manunuzi",
    "sale_date": "tarehe_ya_mauzo",
    "item_name": "jina_la_bidhaa",
    "service_name": "jina_la_huduma",
    "expense_date": "tarehe_ya_matumizi",
    "expense_name": "jina_la_matumizi",
    "amount": "kiasi",
    "remarks": "maelezo",
    "total": "jumla",
    "profit": "faida",
    "category": "aina",
    "current_stock": "stock_iliyopo",
    "minimum_stock": "stock_ya_chini",
    "unit": "kipimo",
    "quantity_sold": "idadi_iliyouzwa",
    "total_sales": "jumla_ya_mauzo",
}


def translate(text):
    if st.session_state.get("language") == "Kiswahili":
        return TRANSLATIONS.get(text, text)
    return text


def format_column_heading(column):
    return translate(str(column)).replace("_", " ").title()


def localize_df(df):
    return df.rename(columns={col: format_column_heading(col) for col in df.columns})


def pin_language_selector_to_sidebar_bottom():
    st.markdown(
        """
        <style>
        section[data-testid="stSidebar"] {
            padding-bottom: 7rem;
        }
        section[data-testid="stSidebar"] .st-key-language,
        section[data-testid="stSidebar"] div[data-testid="stVerticalBlock"] > div:last-child {
            position: fixed;
            bottom: 1rem;
            width: 16rem;
            z-index: 10;
            background: var(--background-color);
            padding-top: 0.25rem;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


init_db()

if "language" not in st.session_state:
    st.session_state.language = "English"
_ = translate
pin_language_selector_to_sidebar_bottom()

st.title(_("TallyUp"))
st.caption(_("A simple stock, sales, expense, and profit tracker for a small stationery business."))

menu_items = ["Dashboard", "Inventory/Stock", "Sales", "Expenses", "Reports", "Export Data"]
menu_labels = {_(item): item for item in menu_items}
menu = menu_labels[
    st.sidebar.radio(
        _("Menu"),
        list(menu_labels.keys()),
    )
]

# Dashboard
if menu == "Dashboard":
    today = str(date.today())
    items = get_items_df()
    goods_sales_today = query_df("SELECT COALESCE(SUM(total_amount),0) AS total FROM sales WHERE sale_date=%s", (today,)).iloc[0]["total"]
    goods_profit_today = query_df("SELECT COALESCE(SUM(estimated_profit),0) AS total FROM sales WHERE sale_date=%s", (today,)).iloc[0]["total"]
    service_sales_today = query_df("SELECT COALESCE(SUM(total_amount),0) AS total FROM service_sales WHERE sale_date=%s", (today,)).iloc[0]["total"]
    sales_today = goods_sales_today + service_sales_today
    profit_today = goods_profit_today + service_sales_today
    expenses_today = query_df("SELECT COALESCE(SUM(amount),0) AS total FROM expenses WHERE expense_date=%s", (today,)).iloc[0]["total"]
    low_stock_count = 0 if items.empty else int((items["current_stock"] <= 0).sum())

    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric(_("Sales Today"), money(sales_today))
    c2.metric(_("Estimated Profit Today"), money(profit_today))
    c3.metric(_("Expenses Today"), money(expenses_today))
    c4.metric(_("Service Sales Today"), money(service_sales_today))
    c5.metric(_("Low Stock Items"), low_stock_count)

    st.subheader(_("Low Stock Alerts"))
    if items.empty:
        st.info(_("No items yet. Add your first stock entry from the Inventory/Stock page."))
    else:
        low_stock = items[items["current_stock"] <= 0][["item_name", "current_stock"]]
        if low_stock.empty:
            st.success(_("All items are above their minimum stock level."))
        else:
            st.dataframe(localize_df(low_stock), use_container_width=True, hide_index=True)

    st.subheader(_("Today's Sales"))
    today_goods_sales = query_df("""
        SELECT s.sale_date AS date, i.item_name AS name, s.quantity, s.selling_price, s.total_amount,
               s.estimated_profit
        FROM sales s JOIN items i ON i.item_id = s.item_id
        WHERE s.sale_date = %s
        ORDER BY s.sale_id DESC
    """, (today,))
    today_service_sales = query_df("""
        SELECT sale_date AS date, service_name AS name, quantity, selling_price,
               total_amount, total_amount AS estimated_profit
        FROM service_sales
        WHERE sale_date = %s
        ORDER BY service_sale_id DESC
    """, (today,))
    today_sales = pd.concat([today_goods_sales, today_service_sales], ignore_index=True)
    st.dataframe(localize_df(today_sales), use_container_width=True, hide_index=True)

# Inventory / Stock
elif menu == "Inventory/Stock":
    st.subheader(_("Inventory / Stock"))
    with st.form("stock_form"):
        c1, c2 = st.columns(2)
        purchase_date = c1.date_input(_("Date"), value=date.today())
        item_name = c2.text_input(_("Item Name"), placeholder="Blue Pen")
        c3, c4, c5 = st.columns(3)
        buying_price = c3.number_input(_("Buying Price"), min_value=0.0, step=100.0)
        quantity = c4.number_input(_("Quantity"), min_value=0.0, step=1.0)
        total_cost = buying_price * quantity
        c5.metric(_("Total Cost"), money(total_cost))
        submitted = st.form_submit_button(_("Save Stock"))

    if submitted:
        clean_name = item_name.strip()
        if not clean_name:
            st.error(_("Item name is required."))
        elif buying_price <= 0 or quantity <= 0:
            st.error(_("Buying price and quantity must be greater than zero."))
        else:
            conn = get_conn()
            cur = conn.cursor()
            try:
                cur.execute("SELECT item_id FROM items WHERE item_name = %s", (clean_name,))
                existing = cur.fetchone()
                if existing:
                    item_id = existing[0]
                    cur.execute(
                        "UPDATE items SET current_stock = current_stock + %s, buying_price=%s WHERE item_id=%s",
                        (quantity, buying_price, item_id),
                    )
                else:
                    cur.execute(
                        """
                        INSERT INTO items (item_name, buying_price, current_stock)
                        VALUES (%s, %s, %s)
                        RETURNING item_id
                        """,
                        (clean_name, buying_price, quantity),
                    )
                    item_id = cur.fetchone()[0]

                cur.execute(
                    """
                    INSERT INTO purchases (purchase_date, item_id, quantity, buying_price, total_cost)
                    VALUES (%s, %s, %s, %s, %s)
                    """,
                    (str(purchase_date), item_id, quantity, buying_price, total_cost),
                )
                conn.commit()
            except Exception:
                conn.rollback()
                raise
            finally:
                cur.close()
                release_conn(conn)
            st.cache_data.clear()
            st.success(_("Stock saved."))
            st.rerun()

    st.subheader(_("Current Stock"))
    stock = query_df("""
        SELECT item_name AS name, buying_price, current_stock AS quantity,
               buying_price * current_stock AS stock_value
        FROM items
        ORDER BY item_name
    """)
    st.dataframe(localize_df(stock), use_container_width=True, hide_index=True)

    st.subheader(_("Stock History"))
    purchases = query_df("""
        SELECT p.purchase_date AS date, i.item_name AS name, p.buying_price,
               p.quantity, p.total_cost
        FROM purchases p JOIN items i ON i.item_id = p.item_id
        ORDER BY p.purchase_date DESC, p.purchase_id DESC
        LIMIT 100
    """)
    st.dataframe(localize_df(purchases), use_container_width=True, hide_index=True)

# Sales
elif menu == "Sales":
    st.subheader(_("Sales"))
    sale_type_options = {_("Goods"): "Goods", _("Service"): "Service"}
    sale_type = sale_type_options[
        st.radio(_("Sale Type"), list(sale_type_options.keys()), horizontal=True)
    ]

    if sale_type == "Goods":
        mapping, options = get_item_options()
        if not options:
            st.warning(_("Add stock first before recording goods sales."))
        else:
            items_df = get_items_df()
            with st.form("goods_sale_form"):
                sale_date = st.date_input(_("Date"), value=date.today())
                item_label = st.selectbox(_("Name"), options)
                item_id = mapping[item_label]
                item_row = items_df[items_df["item_id"] == item_id].iloc[0]
                st.info(f"{_('Available stock')}: {item_row['current_stock']}")
                c1, c2, c3 = st.columns(3)
                selling_price = c1.number_input(_("Selling Price"), min_value=0.0, value=float(item_row["selling_price"]), step=100.0)
                quantity = c2.number_input(_("Quantity"), min_value=0.0, step=1.0)
                total_amount = selling_price * quantity
                c3.metric(_("Total"), money(total_amount))
                submitted = st.form_submit_button(_("Save Sale"))
            if submitted:
                if selling_price <= 0 or quantity <= 0:
                    st.error(_("Selling price and quantity must be greater than zero."))
                elif quantity > float(item_row["current_stock"]):
                    st.error(_("You cannot sell more than the available stock."))
                else:
                    buying_price_at_sale = float(item_row["buying_price"])
                    estimated_profit = (selling_price - buying_price_at_sale) * quantity
                    conn = get_conn()
                    cur = conn.cursor()
                    try:
                        cur.execute(
                            """
                            INSERT INTO sales (sale_date, item_id, quantity, selling_price, total_amount, estimated_profit)
                            VALUES (%s, %s, %s, %s, %s, %s)
                            """,
                            (str(sale_date), item_id, quantity, selling_price, total_amount, estimated_profit),
                        )
                        cur.execute(
                            "UPDATE items SET current_stock = current_stock - %s, selling_price=%s WHERE item_id=%s",
                            (quantity, selling_price, item_id),
                        )
                        conn.commit()
                    except Exception:
                        conn.rollback()
                        raise
                    finally:
                        cur.close()
                        release_conn(conn)
                    st.cache_data.clear()
                    st.success(_("Sale saved and stock updated."))
                    st.rerun()
    else:
        with st.form("service_sale_form"):
            c1, c2 = st.columns(2)
            sale_date = c1.date_input(_("Date"), value=date.today())
            service_name = c2.text_input(_("Name"), placeholder="Printing, typing, photocopy...")
            c3, c4, c5 = st.columns(3)
            selling_price = c3.number_input(_("Selling Price"), min_value=0.0, step=100.0)
            quantity = c4.number_input(_("Quantity"), min_value=0.0, value=1.0, step=1.0)
            total_amount = selling_price * quantity
            c5.metric(_("Total"), money(total_amount))
            submitted = st.form_submit_button(_("Save Service Sale"))
        if submitted:
            clean_name = service_name.strip()
            if not clean_name:
                st.error(_("Name is required."))
            elif selling_price <= 0 or quantity <= 0:
                st.error(_("Selling price and quantity must be greater than zero."))
            else:
                execute(
                    """
                    INSERT INTO service_sales (sale_date, service_name, selling_price, quantity, total_amount)
                    VALUES (%s, %s, %s, %s, %s)
                    """,
                    (str(sale_date), clean_name, selling_price, quantity, total_amount),
                )
                st.success(_("Service sale saved."))
                st.rerun()

    st.subheader(_("Goods Sales"))
    goods_sales = query_df("""
        SELECT s.sale_date AS date, i.item_name AS name, s.selling_price,
               s.quantity, s.total_amount AS total
        FROM sales s JOIN items i ON i.item_id = s.item_id
        ORDER BY s.sale_date DESC, s.sale_id DESC
        LIMIT 100
    """)
    st.dataframe(localize_df(goods_sales), use_container_width=True, hide_index=True)

    st.subheader(_("Service Sales"))
    service_sales = query_df("""
        SELECT sale_date AS date, service_name AS name, selling_price,
               quantity, total_amount AS total
        FROM service_sales
        ORDER BY sale_date DESC, service_sale_id DESC
        LIMIT 100
    """)
    st.dataframe(localize_df(service_sales), use_container_width=True, hide_index=True)

# Expenses
elif menu == "Expenses":
    st.subheader(_("Record Expense"))
    with st.form("expense_form"):
        expense_date = st.date_input(_("Expense Date"), value=date.today())
        expense_name = st.text_input(_("Expense Name"), placeholder="Transport, rent, packaging...")
        amount = st.number_input(_("Amount"), min_value=0.0, step=100.0)
        remarks = st.text_area(_("Remarks"), placeholder=_("Optional"))
        submitted = st.form_submit_button(_("Save Expense"))
    if submitted:
        if not expense_name.strip() or amount <= 0:
            st.error(_("Expense name and amount are required."))
        else:
            execute(
                "INSERT INTO expenses (expense_date, expense_name, amount, remarks) VALUES (%s, %s, %s, %s)",
                (str(expense_date), expense_name.strip(), amount, remarks),
            )
            st.success(_("Expense saved."))
            st.rerun()

    st.subheader(_("Recent Expenses"))
    df = query_df("SELECT * FROM expenses ORDER BY expense_date DESC, expense_id DESC LIMIT 100")
    st.dataframe(localize_df(df), use_container_width=True, hide_index=True)

# Reports
elif menu == "Reports":
    st.subheader(_("Reports"))
    c1, c2 = st.columns(2)
    start_date = c1.date_input(_("Start Date"), value=date.today().replace(day=1))
    end_date = c2.date_input(_("End Date"), value=date.today())

    sales = query_df("""
        SELECT s.sale_date, i.item_name, s.quantity, s.selling_price,
               s.total_amount, s.estimated_profit
        FROM sales s JOIN items i ON i.item_id = s.item_id
        WHERE s.sale_date BETWEEN %s AND %s
        ORDER BY s.sale_date DESC, s.sale_id DESC
    """, (str(start_date), str(end_date)))

    service_sales = query_df("""
        SELECT sale_date, service_name, quantity, selling_price,
               total_amount, total_amount AS estimated_profit
        FROM service_sales
        WHERE sale_date BETWEEN %s AND %s
        ORDER BY sale_date DESC, service_sale_id DESC
    """, (str(start_date), str(end_date)))

    purchases = query_df("""
        SELECT p.purchase_date, i.item_name, p.quantity, p.buying_price,
               p.total_cost
        FROM purchases p JOIN items i ON i.item_id = p.item_id
        WHERE p.purchase_date BETWEEN %s AND %s
        ORDER BY p.purchase_date DESC, p.purchase_id DESC
    """, (str(start_date), str(end_date)))

    expenses = query_df("""
        SELECT expense_date, expense_name, amount, remarks
        FROM expenses
        WHERE expense_date BETWEEN %s AND %s
        ORDER BY expense_date DESC, expense_id DESC
    """, (str(start_date), str(end_date)))

    goods_total_sales = sales["total_amount"].sum() if not sales.empty else 0
    service_total_sales = service_sales["total_amount"].sum() if not service_sales.empty else 0
    total_sales = goods_total_sales + service_total_sales
    goods_total_profit = sales["estimated_profit"].sum() if not sales.empty else 0
    total_profit = goods_total_profit + service_total_sales
    total_expenses = expenses["amount"].sum() if not expenses.empty else 0
    net_profit = total_profit - total_expenses
    total_purchases = purchases["total_cost"].sum() if not purchases.empty else 0

    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric(_("Sales"), money(total_sales))
    c2.metric(_("Estimated Gross Profit"), money(total_profit))
    c3.metric(_("Expenses"), money(total_expenses))
    c4.metric(_("Estimated Net Profit"), money(net_profit))
    c5.metric(_("Purchases"), money(total_purchases))

    st.markdown(f"### {_('Goods Sales Report')}")
    st.dataframe(localize_df(sales), use_container_width=True, hide_index=True)

    st.markdown(f"### {_('Service Sales Report')}")
    st.dataframe(localize_df(service_sales), use_container_width=True, hide_index=True)

    st.markdown(f"### {_('Inventory / Stock Report')}")
    st.dataframe(localize_df(purchases), use_container_width=True, hide_index=True)

    st.markdown(f"### {_('Expenses Report')}")
    st.dataframe(localize_df(expenses), use_container_width=True, hide_index=True)

    st.markdown(f"### {_('Fast Moving Items')}")
    fast = query_df("""
        SELECT i.item_name, SUM(s.quantity) AS quantity_sold, SUM(s.total_amount) AS total_sales
        FROM sales s JOIN items i ON i.item_id = s.item_id
        WHERE s.sale_date BETWEEN %s AND %s
        GROUP BY i.item_id, i.item_name
        ORDER BY quantity_sold DESC
    """, (str(start_date), str(end_date)))
    st.dataframe(localize_df(fast), use_container_width=True, hide_index=True)

# Export
elif menu == "Export Data":
    st.subheader(_("Export Data"))
    st.write(_("Download your business records as Excel files."))

    data = {
        "Current Stock": query_df("""
            SELECT item_name AS name, buying_price, current_stock AS quantity,
                   buying_price * current_stock AS stock_value
            FROM items
            ORDER BY item_name
        """),
        "Inventory Stock": query_df("""
            SELECT p.purchase_date AS date, i.item_name AS name, p.buying_price,
                   p.quantity, p.total_cost
            FROM purchases p JOIN items i ON i.item_id=p.item_id
            ORDER BY p.purchase_date DESC, p.purchase_id DESC
        """),
        "Goods Sales": query_df("""
            SELECT s.sale_date AS date, i.item_name AS name, s.selling_price,
                   s.quantity, s.total_amount AS total, s.estimated_profit
            FROM sales s JOIN items i ON i.item_id=s.item_id
            ORDER BY s.sale_date DESC, s.sale_id DESC
        """),
        "Service Sales": query_df("""
            SELECT sale_date AS date, service_name AS name, selling_price,
                   quantity, total_amount AS total, total_amount AS profit
            FROM service_sales
            ORDER BY sale_date DESC, service_sale_id DESC
        """),
        "Expenses": query_df("SELECT * FROM expenses ORDER BY expense_date DESC"),
    }

    export_file = BytesIO()
    with pd.ExcelWriter(export_file, engine="openpyxl") as writer:
        for sheet, df in data.items():
            localize_df(df).to_excel(writer, index=False, sheet_name=sheet[:31])
    export_file.seek(0)

    st.download_button(
        _("Download Excel Export"),
        data=export_file,
        file_name=f"tallyup_export_{datetime.now().strftime('%Y%m%d_%H%M')}.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )

st.sidebar.markdown("---")
st.sidebar.caption(_("TallyUp") + " v1")
st.sidebar.selectbox("Language / Lugha", ["English", "Kiswahili"], key="language")
